version: "3"

services:
  postgres:
    container_name: inmana-postgres
    image: postgres:13
    restart: "no"
    environment:
      POSTGRES_DB: inmana
      POSTGRES_USER: marciorasf
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - ./resources/postgresql:/var/lib/postgresql/data

volumes:
  postgres:
