version: "3"

services:
  postgres:
    container_name: inmana-dev-postgres
    image: postgres:13
    restart: "no"
    environment:
      POSTGRES_DB: inmana_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./resources/postgresql:/var/lib/postgresql/data

volumes:
  postgres:
